spring.datasource.url=jdbc:mysql://localhost:3306/menshop
spring.datasource.username=root
spring.datasource.password=322005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=3a58b1e2512a2c337fd9dfd862fc91dbab6ade09fbf63275541e6fbcdf7976da
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manhkha03020100@gmail.com
spring.mail.password=aqscukjlyupmkvfq
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

vnpay.tmn-code=G6MZC9MI
vnpay.hash-secret=0VA9BWVNKXTOHXTPIH2XZ3J0FXBW5Y8N
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3000/thanh-toan/vnpay-return

# GOOGLE OAUTH2
spring.security.oauth2.client.registration.google.client-id=479479185111-i5mhsq47u79nqrll7k2q0hoam2hpikh1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
app.oauth2.redirect-uri=http://localhost:3000/oauth2/success

ai.server.url=http://127.0.0.1:8000